export const AUTH_START = "AUTH_START";
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_MESSAGE_ERROR_RESET = "AUTH_MESSAGE_ERROR_RESET";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_PROFILE_UPDATE_START = "AUTH_PROFILE_UPDATE_START";
export const AUTH_PROFILE_UPDATE_SUCCESS = "AUTH_PROFILE_UPDATE_SUCCESS";
export const AUTH_PROFILE_UPDATE_FAILED = "AUTH_PROFILE_UPDATE_FAILED";
export const AUTH_PROFILE_UPDATE_COMPLETE = "AUTH_PROFILE_UPDATE_COMPLETE";

export const USER_DATA_UPDATE = "USER_DATA_UPDATE";