export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const AUTH_PROFILE_UPDATE_START = "AUTH_PROFILE_UPDATE_START";
export const AUTH_PROFILE_UPDATE_SUCCESS = "AUTH_PROFILE_UPDATE_SUCCESS";
export const AUTH_PROFILE_UPDATE_FAILED = "AUTH_PROFILE_UPDATE_FAILED";
export const AUTH_PROFILE_UPDATE_COMPLETE = "AUTH_PROFILE_UPDATE_COMPLETE";